#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
verbose=
if [ $1 == "-v" ]; then
  shift
  verbose="-verbose"
fi
exec sail -plugin "$DIR/_build/default/sail_rust_backend/sail_plugin_rust.cmxs" -rust $verbose $*
